name: Update Holidays Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every week (Sunday at midnight)
  push:
    branches:
      - data  # Optional: also run the workflow on push to the data branch
  workflow_dispatch:

jobs:
  fetch_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: data  # Checkout the data branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests
        run: pip install requests

      - name: Run Python Script
        run: python snapshot_holidays.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/*.json
          git commit -m 'Update holiday data'
          git push origin data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
